services:
  frontend:
    build:
      context: frontend-ng
      target: prod
    ports:
      - 5173:80
    volumes:
      - ./frontend-ng/:/usr/src/app/
    restart: always
    depends_on:
      - backend
  backend:
    build:
      context: .
      target: prod
    volumes:
      - ./:/app/
      - ./roadrecon.db:/app/roadrecon.db
    ports:
      - 5000:5000
    restart: always
