services:
  frontend:
    build:
      context: frontend-ng
    ports:
      - 5173:5173
    volumes:
      - ./frontend-ng/:/usr/src/app/
    restart: always
  backend:
    build:
      context: .
    volumes:
      - ./:/app/
      - ./roadrecon.db:/app/roadrecon.db
    ports:
      - 5000:5000
    restart: always
