services:
  frontend:
    build:
      context: frontend-ng
    network_mode: "host"
    volumes:
      - ./frontend-ng/:/usr/src/app/
  backend:
    build:
      context: .
    volumes:
      - ./roadrecon.db:/app/roadrecon.db
    network_mode: "host"
